server:
  port: 9091

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: true 
    wait-time-in-ms-when-sync-empty: 3000
    evictionIntervalTimerInMs: 60000 